#!/usr/bin/env bash
# Redirects to youtube for /redirect_me route
read -r -d '' CONFIG << EOM
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /redirect_me {
            return 301 \$scheme:https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        location / {
            try_files \$uri \$uri/ =404;
        }
}
EOM
echo "$CONFIG" | sudo tee /etc/nginx/sites-available/default
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx restart
sudo nginx -s reload
