#!/usr/bin/env bash
# Installs nginx with 301

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo touch /var/www/html/error404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo service nginx restart
search_str="^\tlocation / {"
replace_str="\terror_bage 404 /error404.html;\n\n\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sudo sed -i "s@${search_str}@${replace_str}@" /etc/nginx/sites-available/default
sudo service nginx restart
