#!/usr/bin/env bash
# Installs and configures load balancer 
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y haproxy

read -r -d '' CONFIG <<- EOM
frontend http_web
    bind *:80
    stats uri /haproxy?stats
    default_backend web_backend

backend web_backend
    balance roundrobin
    server web01 54.167.16.173:80 check
    server web022 52.91.225.194:80 check
EOM
sed -n '/frontend http_web/q;p' /etc/haproxy/haproxy.cfg | sudo tee /etc/haproxy/haproxy.cfg
echo "$CONFIG" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
