#!/usr/bin/env bash
# Prints Holberton School x 10 with while loop
n=0
while [ "$n" -lt 10 ]; do
    if [ "$n" -eq 8 ];
    then 
      echo "Hi";
    else
      echo "Holberton School";
    fi
    n=$(( n + 1))
done
