#!/usr/bin/env bash
# Installs and starts apache server w/ default response
sudo apt-get update -y
sudo apt-get install -y apache2
sudo ufw allow 'Apache Full'
sudo echo "ServerName localhost" > /etc/apache2.conf
sudo echo "Hello Holberton" > /var/www/html/index.html
sudo service apache2 start
