#!/usr/bin/env bash
# Installs and starts apache server w/ default response
sudo apt-get update -y
sudo apt-get install -y apache2
sudo ufw allow 'Apache Full'
echo "ServerName localhost" | sudo tee /etc/apache2.conf
echo "Hello Holberton" | sudo tee /var/www/html/index.html
sudo service apache2 start
